### ISSUE TITLE
running yamp with docker

### ISSUE THREAD

**Issue by sbastkowski** [alesssia/YAMP#1]
Hi,
I am trying to run the yamp workflow within the docker container. I run:
docker pull alesssia/yampdocker
and then 
nextflow run YAMP.nf --reads1 ERR011089_1.fastq.gz --reads2 ERR011089_1.fastq.gz --prefix Meta_HIT_ERR011089 --outdir ./data --mode complete -with-docker yampdocker

as described in the instructions. I get the following error:
nextflow: command not found

Do I need to install nextflow manually? From the description it seems to me like nextflow is available through the docker container. If it is, is there a step missing? How do I start the docker, as the ways suggested by the docker help, didn't seem to work.

**Comment by alesssia** [comment]
Hello,
yes, you need to install Nextflow manually. To do so, you should go to a directory of your choice and run (from the terminal window) the following instruction: `wget -qO- get.nextflow.io | bash`. This will create the nextflow main executable file in the directory you are in  (more info here: [https://www.nextflow.io/docs/latest/getstarted.html](https://www.nextflow.io/docs/latest/getstarted.html)). 
Please note that if you want to run nextflow as done in the example (that is without specifying the executable path) you also need to add the directory in which you installed nextflow to your `$PATH` variable (in bash, for instance, as: `export PATH=$PATH:/path/to/dir`).
Nextflow will take care of the processes, running them within the Docker container (so no need to run Docker yourself).

I am now updating the tutorial :)
