### ISSUE TITLE
Dockerfile with Miniconda3 (Python3)

### ISSUE THREAD

**Issue by junaruga** [alesssia/YAMP#11]
Hello,

Seeing your `Dockerfile`, the environment is created by Miniconda2 (Python 2).
https://github.com/alesssia/YAMP/blob/master/yampdocker/Dockerfile

As Python2 support will be finished at 2020 (Remaining 9 months), 
https://pythonclock.org/

Is it possible to update the `Dockerfile` with Miniconda 3 (Python 3) and newer version dependencies?

https://repo.continuum.io/miniconda/
`Miniconda3-*-Linux-x86.sh`

When upgrading it, as it seems that qiime 1.x only supports Python2, you might have to change it to `qiime2`.

https://docs.qiime2.org/2019.1/install/
https://anaconda.org/qiime2/qiime2

Thanks!

**Comment by alesssia** [comment]
Hi @junaruga ,

I am waiting for HUMAnN2 to release the new updates (early 2020, it seems) to migrate everything on Miniconda3, since HUMAnN2 still requires Python 2.7 (at least in Conda).

Sorry about this!

**Comment by junaruga** [comment]
Sure. thanks for working about the HUMAnN2 and Miniconda3.

**Comment by alesssia** [comment]
Updated to a new version of YAMP that uses a multi-container scenario (and solves the Python/Miniconda version issue)
