### ISSUE TITLE
humann not in the  biobaker container

### ISSUE THREAD

**Issue by poquirion** [alesssia/YAMP#23]
I have downloaded the workflow at the tip of master, downloaded the containers  and ran the test with singularity 
```
nextflow run YAMP.nf -profile test,sigularity
```
and I get the following error

```
[...]
Command executed:

  echo 0.9.5.3 > v_pipeline.txt
  echo 21.04.3 > v_nextflow.txt
  
  echo quay.io/biocontainers/fastqc:0.11.9--0 | cut -d: -f 2 > v_fastqc.txt
  echo quay.io/biocontainers/bbmap:38.87--h1296035_0 | cut -d: -f 2 > v_bbmap.txt
  
  metaphlan --version > v_metaphlan.txt
  humann --version > v_humann.txt
  //echo qiime2/core:2020.8 | cut -d: -f 2 > v_qiime.txt
  
  echo quay.io/biocontainers/multiqc:1.9--py_1 | cut -d: -f 2 > v_multiqc.txt
  
  scrape_software_versions.py > software_versions_mqc.yaml

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 9: humann: command not found

[...]
```
and indeed container params.singularity_container_biobaker defined for this step does not contain the humann tool.
 

```
[YAMP]$ singularity exec ~/Singularity_images/metaphlanv3.0.7  humann  --version 
FATAL:   "humann": executable file not found in $PATH
```

**Comment by alesssia** [comment]
Hi @poquirion ,

how did you download the containers? The container used by YAMP is `biobakery/workflows:3.0.0.a.6.metaphlanv3.0.7` and not `metaphlanv3.0.7`. Have you renamed it? Or did you download a container that includes only metaphlan v 3.0.7 and not the entire biobakery (that is, also humann)?

**Comment by poquirion** [comment]
Thanks, I am debugging for a third party, so I can't tell for sure that we are using the right singularity image.  I will make sure that the `.sif` is rebuilt from biobakery/workflows:3.0.0.a.6.metaphlanv3.0.7.

**Comment by poquirion** [comment]
Ok, it works with the right image.
