### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by richardjdavies** [alesssia/YAMP#3]
Hi Alessia,

Thanks for our chat on Thursday. I've now successfully done the YAMP tutorial - it was indeed easy to use and portable!

Here are some documentation updates - I can't send a pull request for the Wiki unfortunately ;-(

At https://github.com/alesssia/YAMP/wiki/How-to-run-YAMP
- In nextflow.config on a local machine, executor and queue should be commented with `//` not `#`
- The example command to run YAMP should have `--reads2 ./data/ERR011089_2.fastq.gz` not `_1` again

At https://github.com/alesssia/YAMP/wiki/Getting-started
- The dependencies should note that Nextflow requires Java < 9, at least until https://github.com/nextflow-io/nextflow/issues/462 is fixed
- I found the database files confusing. Here's the layout which ended up working for me with the default `nextflow.config`. I think you could show this layout explicitly on this page

```
$ ls -R resources/
resources/:
adapters.fa
bowtie2db/
chocophlan/
hg19_main_mask_ribo_animal_allplant_allfungus.fa.gz
phix174_ill.ref.fa.gz
ref/
sequencing_artifacts.fa.gz
uniref/

resources/bowtie2db:
db_v20/

resources/bowtie2db/db_v20:
mpa_v20_m200.1.bt2
mpa_v20_m200.2.bt2
mpa_v20_m200.3.bt2
mpa_v20_m200.4.bt2
mpa_v20_m200.pkl
mpa_v20_m200.rev.1.bt2
mpa_v20_m200.rev.2.bt2

resources/chocophlan:
g__Abiotrophia.s__Abiotrophia_defectiva.centroids.v0.1.1.ffn.gz
g__Acaricomes.s__Acaricomes_phytoseiuli.centroids.v0.1.1.ffn.gz
(many more files)

resources/ref:
genome/
index/

resources/ref/genome:
1/

resources/ref/genome/1:
chr1.chrom.gz
chr2.chrom.gz
chr3.chrom.gz
chr4.chrom.gz
chr5.chrom.gz
chr6.chrom.gz
chr7.chrom.gz
info.txt
scaffolds.txt.gz
summary.txt

resources/ref/index:
1/

resources/ref/index/1:
chr1-3_index_k13_c2_b1.block
chr1-3_index_k13_c2_b1.block2.gz
chr4-7_index_k13_c2_b1.block
chr4-7_index_k13_c2_b1.block2.gz

resources/uniref:
uniref90/

resources/uniref/uniref90:
uniref90_annotated.1.1.dmnd
```

Thanks!

Richard.

**Comment by alesssia** [comment]
Hi @richardjdavies,
thanks for these suggestions, I have implemented them in the wiki and in the README file!
