### ISSUE TITLE
memory limit

### ISSUE THREAD

**Issue by SilasK** [alesssia/YAMP#4]
I'm trying to use YAMP on samples from mouse meta-genome samples. So I downloaded the mouse genome.

During the decontamination step I get a memory error. So I increased the memory limit. Now I'd like to use a higher memory limit for each step, so I don't have to wait too long on the queuing systems. 

I found out there are different variables one for `$mexmem` and another to define the memory fore each process. Do you know hot to use only one variable for both?

**Comment by alesssia** [comment]
Hello @SilasK,

I just committed a new version that should solve this issue. With this version, you don't need to set up a global number or threads/max memory, but each process will read the correct values directly from the configuration file (`nextflow.config`), so you can define different values for each process.

Can you please let me know if this is what you need, so I can close the issue?

P.S. mouse metagenome? cool!
