### ISSUE TITLE
Deduplication

### ISSUE THREAD

**Issue by SilasK** [alesssia/YAMP#5]
Hey alessia,
I've seen sou are using clumpify to deduplicate the reads. Don't you think it would be better to do it after quality control instead on the raw reads?

**Comment by alesssia** [comment]
Hello Silas,
we perform de-duplication on the raw reads because trimming, by modifying the reads' sequence, may potentially mask true duplicates or generate false ones. Why do you suggest performing it afterwards?

**Comment by SilasK** [comment]
According to the processing guide of bbmap, they suggest reduplication after trimming. I asked in the forum and they told me that this guide was written before clumpify. So you are right.

**Comment by alesssia** [comment]
:thumbsup: and thanks for letting me know about this. It is always useful to discuss (IMHO, no discussions == no improvements) :)
