### ISSUE TITLE
some documentation suggestions

### ISSUE THREAD

**Issue by will-rowe** [alesssia/YAMP#6]
Hi Alessia,

Firstly, thank you for releasing this pipeline - it's a good workflow and is working nicely for us.

I just had a couple of suggestions after having installed and run YAMP on a few different systems. I thought it might be useful to make a note here in case others were having the same difficulties.

* the `--prefix` option can't contain a `#`
    - I found this out as I was using seq data basenames as a prefix (e.g. --prefix 123_4#5) . It's not a big problem but caused a bit of headache as there was no error message (pipeline just terminated early)

* contam_15 contains a `P` char in `sequencing_artifacts.fa` in downloaded resources
    - BBMap (v 37.02) didn't like this and the pipeline would through an error.

* really minor again but the uniref path path in `nextflow.config` did not match the resources dir structure (when everything else did)

Thanks again (and sorry if I have missed these points anywhere in the wiki already).

Will

**Comment by alesssia** [comment]
Hi @will-rowe,

thanks for your feedback!
 
I've now added a Troubleshooting page to the wiki [here](https://github.com/alesssia/YAMP/wiki/Troubleshooting), and also fixed the uniref path in the [Folder layout example](https://github.com/alesssia/YAMP/wiki/Folders-layout-example). Everything should look good now. Thanks a lot for pointing out the `#` problem!

Regarding the second point you raised. I've downloaded the `sequencing_artifacts.fa` from the BBmap webpage (it is one of its _component_) and used it with both BBmap v36.92 and v37.10.  Can you send me more details on the error so I can investigate it?

Thanks a lot,
Alessia

**Comment by will-rowe** [comment]
No worries! Here is how I produce the BBMap error. Although I made a mistake, it was v37.78 (most recent version in bioconda) that causes the error. Downgrading to v37.02 fixes it!

* downloaded `YAMP_resources_20171128.tar.gz`

* followed instructions to index and get the dir layout correct

* ran the example command:
```
../nextflow run YAMP.nf --reads1 ./data/ERR011089_1.fastq.gz --reads2 ./data/ERR011089_2.fastq.gz  --prefix Meta_HIT_ERR011089 --outdir ./data --mode complete
```

* receive this error:
```
java.lang.Exception:
An input file appears to be misformatted:
The character with ASCII code 67 appeared where a base was expected.
Sequence #15
Sequence ID 'contam_15'
Sequence: [65, 67, 65, 67, 71, 84, 67, 84, 71, 65, 65, 67, 84, 67, 80, 65, 71, 84, 67, 65, 67, 78, 71, 65, 84, 67, 71, 71, 65, 65, 71, 65, 71, 67]
ACACGTCTGAACTCPAGTCACNGATCGGAAGAGC
```

Fixed with downgrading BBMap, or remove the P (or edit bbmap commands to fixjunk).

**Comment by alesssia** [comment]
Thanks for the very detailed report! I will look into this tomorrow. 
If I may ask, what are you working on?

**Comment by will-rowe** [comment]
You're welcome. I work at the STFC on a few different metagenomics projects; mainly with gut and soil samples. I'm also working on metagenomics tools for resistome profiling etc.

**Comment by alesssia** [comment]
Sounds cool! 

if you are using YAMP to process soil samples, do you mind sharing some stats on computational requirements? I've run a few datasets to check feasibility, but I'd love to have some more information on real-life scenarios. Also, if you want to share some wisdom on how selecting the best processing parameters for processing non-human samples (we have been working only on gut so far) I may create a wiki page (full credit to you, obviously) that may be helpful to other users. Thanks!

**Comment by will-rowe** [comment]
Sure, happy to send some info on. I plan on doing a set of experiments in a few weeks time so will post the performance when I get it.

Not sure I have any wisdom re. best parameters but I will make some notes over the next few weeks and then see if they are any use to you!

**Comment by alesssia** [comment]
Regarding the open BBmap issue. I've added the problem to the troubleshooting page. Thanks for pointing it out and for accepting to share stats and wisdom!

I am also closing this issue!
