### ISSUE TITLE
BowTie2 database file for MetaPhlAn2

### ISSUE THREAD

**Issue by kviljoen** [alesssia/YAMP#8]
Hi Alessia,

Thanks for making your pipeline available! I'm looking for the the BowTie2 database file for MetaPhlAn2. This file is not available within my MetaPhlAn2 installation and the alternate download link in the user documentation leads to 404 not found error. Could you provide a working link?

Thanks!

**Comment by alesssia** [comment]
Hello!

To the best of my understanding MetaPhlAn2 has been updated, and it is now downloading the DBs at its first run (therefore the linked DB may have been dismissed). You could use the data file I generated and which includes all the DBs (please note that the size of this compressed data file is 16.7 GB) and which you can download either from Zenodo (https://zenodo.org/record/1068229#.Wh7a3rTQqL4), or using the following command:

`wget https://zenodo.org/record/1068229/files/YAMP_resources_20171128.tar.gz`

I the meantime I will look for some DB image or generate one myself. Sorry about this.

**Comment by kviljoen** [comment]
I see, thanks! I haven't actually run it yet, so will see if that works to download the DB.
